---
title: "Instrumentation and Orchestration"
author: "Ali Taqi"
output: pdf_document
---

# Instrumentation

The classification chain of musical instruments goes as follows:

\vspace{-1em}
\begin{align*}
\textbf{[Instrument]} \rightarrow \text{[Pitched/Unpitched]} \rightarrow \text{[Timbral-Material Family]}
\end{align*}

## Percussion

Starting off, the [Unpitched] layer has only 1 element, namely, \textit{unpitched} percussion. Percussion is essential when it comes to rhythm, as it is the backbone of a song's rhythm. Instruments include:

\vspace{-1em}
\begin{align*}
\{[I]\}_{[Unpitched]} = \{\text{Drum set},\space \text{Tamborine}, \space \text{Tabla},\space \text{Gong}\}
\end{align*}
\vspace{-1em}

Conversely, the [Pitched] layer also has its 1 element counterpart, \textit{pitched} percussion. Instruments include:

\vspace{-1em}
\begin{align*}
\{[I]\}_{[Pitched]} = \{\text{Marimba},\space \text{Xylophone},\space \text{Vibrophone},\space \text{Timpani},\space \text{Glockenspiel}, \text{Tubular bells}\}
\end{align*}
\vspace{-1em}

## Nonpercussive Pitched instruments

The [Pitched] layer contains all the other instruments, which is notably more diverse. These instruments are primarily responsible for the harmony element of songs, analogous to how percussion is to the rhythm of a song.

## 1. Strings

Strings are a very popular Timbral-Material element, and themselves are diverse in their mode of [attack] (as in ADSR). We subdivide them on this basis, which yields 3 primary subdivisions

### 1a. Bowed Strings

\vspace{-1em}
\begin{align*}
\{\text{Violin},\space \text{Viola}, \space \text{Cello},\space \text{Double Bass}\}
\end{align*}
\vspace{-1em}

### 1b. Struck Strings

\vspace{-1em}
\begin{align*}
\{\text{Piano},\space \text{Harpsichord}\}
\end{align*}
\vspace{-1em}

### 1c. Plucked Strings


\vspace{-1em}
\begin{align*}
\{\text{Guitar},\space \text{Lute}, \space \text{Mandola},\space \text{Ukelele}\}
\end{align*}
\vspace{-1em}