---
title: "Measure Theory and Harmonics"
author: "Ali Taqi"
output: pdf_document
header-includes:
  - \newcommand{\ben}{\begin{enumerate}}
  - \newcommand{\een}{\end{enumerate}}
  - \newcommand{\Lyd}{\text{Lydian}}
  - \newcommand{\Ion}{\text{Ionian}}
  - \newcommand{\Mly}{\text{Mixolydian}}
  - \newcommand{\Dor}{\text{Dorian}}
  - \newcommand{\Aeo}{\text{Aeolian}}
  - \newcommand{\Phg}{\text{Phyrgian}}
  - \newcommand{\Loc}{\text{Locrian}}
  - \newcommand{\N}{\mathbb{N}}
  - \newcommand{\Z}{\mathbb{Z}}
  - \newcommand{\Q}{\mathbb{Q}}
  - \newcommand{\I}{\mathbb{I}}
  - \newcommand{\J}{\mathcal{J}}
  - \newcommand{\E}{\mathcal{E}}
  - \newcommand{\Prms}{\mathbb{P}}
  - \newcommand{\ZtZ}{\Z/12\Z}
  - \newcommand{\octave}{\sim_{8\text{ve}}}
  - \newcommand{\harm}{\text{Harm}}
  - \newcommand{\st}{\,|\,}
  - \newcommand{\dfn}{\textbf{(Definition) }}
  - \newcommand{\ntn}{\textbf{(Notation) }}
  - \newcommand{\exm}{\textbf{(Example) }}
  - \newcommand{\lma}{\textbf{(Lemma) }}
  - \newcommand{\Hz}{\text{Hz}}
---

# Introduction

This short text is intended to be a measure-theoretic approach to the analysis of harmonics in the paradigm of the p-limit just-intonation tuning system.

# Just Intonation

As opposed to N-tone equal temperament (N-TET), this paper will revolve around the other, now outdated tuning system: p-limit justly t(e)mpered tuning (p-JET).

$\dfn \textbf{p-limit Just Intonation.}$ Given a prime number $p \in \Prms$, we may define a p-limit justly tempered tuning system (p-JET) about a tuning frequency $f_T$ to be the product of $f_T$ and the interval set $\I(p)$. Let $P = \{a_1,a_2,\dots,a_k\}$ be the set of the first $k$ prime numbers such that $\max{(P)} =  a_k = p$. The interval set is defined as:

$$\mathbb{I}(p) = \{\prod_i  {p_i}^{n_i} : p_i \in P, n_i \in \Z \}$$

$\ntn \textbf{p-JET.}$ A p-JET system tuned to $f_T$ is denoted $\J(f_T, \I(p))$

$\exm \textbf{5-limit Just Intonation.}$ A 5-limit just intonation system about a tuning frequency $f_T$ is $\J(f_T, \I(5))$ where $\mathbb{I}(5) = \{2^a 3^b 5^c : a,b,c \in \Z \}$

\newpage

# Prelude: Harmonics and Integers

The harmonic series is defined as the product of some fundamental frequency $f_T$ and the series of natural numbers $\N$. Define the $\textbf{harmonic series}$ of $f$ to be the set: \newline 
$$\text{Harm}[f] = \{nf : n \in \mathbb{N}\}$$

## Harmonic Subsets

Suppose $A \subseteq \N$. Then define the harmonic subset of $f$ with respect to the subset $A$ is the set defined as follows.
\begin{align*}
  \text{Harm}_A [f] 
  &= \{af : a \in A\}
\end{align*}
Now, we have the tools to start defining some basic musical objects. Take the subset $\Delta  = \{1,3,5\}$. Then the harmonic subset with respect to $\Delta$ can be defined as: 
\begin{align*}
  \text{Harm}_{\Delta} [f] 
  &= \{af : a \in \Delta \} \\
	&=\{f,3f,5f\}
\end{align*}
This subset $\Delta$ is the holy grail of consonance, at least in the Western canon: the major triad. The connection between our modern day musical intervals and harmonics will be discussed later. There is also a caveat, which is that there exists no practical tuning system that perfectly captures tonic consonance using A for all elements of some non-trivial scale.

## Harmonics: Primes

The prime numbers is a subset of $\mathbb{N}$, and we denote it the set $\mathbb{P} \subset \mathbb{N}$. Since $\mathbb{P}$ is a proper subset of a naturals, we may derive a unique set of harmonics, called the $\textbf{characteristic harmonics}$ of a fundamental $f$. Namely,
$$   \text{Harm}_\Prms [f] = \{pf : p \in \mathbb{P}\} $$
To understand why this is a significant set, we will motivate the next definition, octave equivalency.

## Harmonics: Octave Equivalency
We may define an equivalence relation $\octave$ on the space of fundamental frequencies, called $\textbf{octave equivalency}$, as follows:

$$ f  \octave \hat{f} \iff \exists K \in \Z : \hat{f} = 2^{K} f $$

The beauty of this relation is that it is cross-cultural, agreed upon in the musical traditions of almost every culture if not all. The quick reasoning for this is because doubling some frequency $f_T$ is the same action as taking the first non-fundamental element from its harmonic series, $2f_T \in \harm [f_T]$.

## Intervals and the Rational Numbers
Now that we have motivated octave equivalency, we may finally expand our musical horizons. Notice, that in the definition of octave equivalency, it suffices to find any $K \in \Z$ such that one frequency is $2^K$ multiples of the other for them to be equivalent. \newline Up until now, our definition of harmonics only utilized the multiplication of frequencies by positive whole numbers $(n \in \N)$. However, as we can see, octave equivalency already requires us to use multiplicative inverses, or in other words, fractions.
  
Now, we may define an extremely powerful and versatile musical object. A $\textbf{justly-intonatated interval}$, about a tonic frequency $f$, is any element of the set: 
$$ \mathbb{I}[f] = \left( \frac{p}{q} \cdot f : \frac{p}{q} \in \Q^+ \backslash \{0,1\} \right) $$
The set of intervals may be further partitioned into two categories as follows:

An interval is $\textit{descending}$ if its interval scalar $pq^{-1} \in (0,1)$, and $\textit{ascending}$ if $pq^{-1} \in (1,\infty)$.
  
## Euler's Consonance Formula
$$ E: \Q^+ \backslash \{0,1\} \rightarrow \N $$
Define an interval as an ordered pair corresponding to its interval scalar as $\iota_i = (p_i,q_i)$. If $E(\iota_0) < E(\iota_1)$, Euler believes that this entails that $\iota_0$ is more $\textbf{consonant}$ than $\iota_1$

