---
title: "Group Theory and the Lydian Chromatic Concept"
author: "Ali Taqi"
output: pdf_document
header-includes:
  - \newcommand{\ben}{\begin{enumerate}}
  - \newcommand{\een}{\end{enumerate}}
  - \newcommand{\Lyd}{\text{Lydian}}
  - \newcommand{\Ion}{\text{Ionian}}
  - \newcommand{\Mly}{\text{Mixolydian}}
  - \newcommand{\Dor}{\text{Dorian}}
  - \newcommand{\Aeo}{\text{Aeolian}}
  - \newcommand{\Phg}{\text{Phyrgian}}
  - \newcommand{\Loc}{\text{Locrian}}
  - \newcommand{\N}{\mathbb{N}}
  - \newcommand{\Z}{\mathbb{Z}}
  - \newcommand{\Q}{\mathbb{Q}}
  - \newcommand{\I}{\mathbb{I}}
  - \newcommand{\J}{\mathcal{J}}
  - \newcommand{\E}{\mathcal{E}}
  - \newcommand{\Prms}{\mathbb{P}}
  - \newcommand{\ZtZ}{\Z/12\Z}
  - \newcommand{\octave}{\sim_{8\text{ve}}}
  - \newcommand{\harm}{\text{Harm}}
  - \newcommand{\st}{\,|\,}
  - \newcommand{\dfn}{\textbf{(Definition) }}
  - \newcommand{\ntn}{\textbf{(Notation) }}
  - \newcommand{\exm}{\textbf{(Example) }}
  - \newcommand{\lma}{\textbf{(Lemma) }}
  - \newcommand{\prf}{\textbf{(Proof) }}
  - \newcommand{\Hz}{\text{Hz}}
---

# Introduction

This short text is intended to be a group-theoretic analysis of some of the results in George Russell's Lydian Chromatic Concept. 

# N-TET

$\dfn \textbf{N-Tone Equal Temperament. }$ Given a positive whole number $N \in \N$, we may define a N-tone equal temperament tuning system (N-TET) about a tuning frequency $f_T$ to be the product of $f_T$ and the interval set $\I(N)$. The interval set is defined as:

$$\mathbb{I}(N) = \{ 2^{\frac{i}{N}}  :  i \in \Z/N\Z \}$$
  
$\ntn \textbf{N-TET.}$ An $N$-TET system tuned to $f_T$ is denoted $\E(f_T, \I(N))$.

$\exm \textbf{12-TET.}$ A 12-TET system tuned to $f_T$ is denoted $\E(f_T, \I(12))$ where $\mathbb{I}(12) = \{ 2^{\frac{i}{N}}  :  i \in \ZtZ \}$

\newpage

# Pitch Groups

$\dfn \textbf{Pitch Subset. }$ Let $\E_{12} = \E(f_T,\I(12))$ be our 12-TET system tuned to $f_T$. Then $\E_{12}' \subseteq {\E_{12}}$ is a pitch subset of $\E_{12}$ if its interval set $\I_{\E_{12} '} \subseteq \I_{\E_{12}} = \I(12)$.

$\exm \textbf{Symmetric Pitch Subsets of Z/12Z.}$ The symmetric pitch subsets of $\ZtZ$ are the tuning systems with interval sets $\I_K = \{ 2^{\frac{iK}{12}}  :  i \in \ZtZ \}$ with values of $K = \{1,2,\dots,6\}$. They are as follows:

\begin{enumerate}
\item $\textit{The Chromatic Scale.}$ Corrosponding to the interval set $\I_1$, the Chromatic Scale is actually equal to $\I(12)$.
\item $\textit{The Whole Tone Scales. }$ Corrosponding to the interval set $\I_2$, the Whole Tone Scales divide the interval set of $\E_{12}$ into the two sets $\I_2(0)$ and $\I_2(1)$ where $\I_2(t) = \{ 2^{\frac{i}{6} + t} :  i \in \Z/6\Z \}$. Note that we can also just say $t \in \Z/2\Z$. 

Generally, we can say that given $t = K$ symmetric pitch subsets $\I_K(t)$ of size $N/K$, we have $t \in \Z/K\Z$.

\item $\textit{The Diminished Scales.}$ Corrosponding to the interval set $\I_3$, the Diminished Scales divide the interval set of $\E_{12}$ into the three sets: 
$$\I_3(t) = \{ 2^{\frac{i}{4} + t}  :  i \in \Z/4\Z \} \st t \in \Z/3\Z$$
\item $\textit{The Augmented Scales.}$ Corrosponding to the interval set $\I_4$, the Augmented Scales divide the interval set of $\E_{12}$ into the four sets:
$$\I_4(t) = \{ 2^{\frac{i}{3} + t}  :  i \in \Z/3\Z \} \st t \in \Z/4\Z$$
\item $\textit{The}$ $\phi$$\textit{-Sequence}$. Corrosponding to the interval set $\I_5$, the coprimality of $5$ and $12$ leads to the $\phi$-Sequence being a unique reordering of $\I(12)$:
$$\I_\phi = \{ 2^{\frac{5i}{12}}  :  i \in \ZtZ \}$$
\item $\textit{The Tritones.}$ Corrosponding to the interval set $\I_6$, the Tritones divide the interval set of $\E_{12}$ into the six sets: $$\I_6(t) = \{ 2^{\frac{i}{2} + t}  :  i \in \Z/2\Z \} \st t \in \Z/6\Z$$
\end{enumerate}

\newpage

# Various Results

$\lma \textbf{Tritone Existence.}$ Suppose we have an N-TET system $\E_{N}$ tuned to $f_T$ where $N$ is an even number ($N\text{ mod }2 \equiv 0$). Then $\sqrt{2} \in \I_{\E_{N}}$. That is:
$$\exists K \in \N : \E_{N} = \E(2K) \iff \iota_{\delta} \in \I_{\E_1} \text{ where } \iota_{\delta} = \sqrt{2}$$.
Proof: If $N$ is even, then $N/2 \in \Z/N\Z$. This means $\iota = 2^{\frac{N/2}{N}} = 2^{\frac{1}{2}} \in \I(N).$

$\textbf{Question.}$ What if we did a fifth equivalence relation and have a $(N,p)$ TET system where the interval set not only partitions the octave equally but also the perfect fifth. So:
$$\I (N,p) = \{ 2^{i/N} 3^{i/N} : N \in \Z/N\Z  \}$$



